---
- name: Install development packages
  apt:
    pkg:
    - git
    - neovim
    - emacs
    - jq
    - ripgrep
    - podman
    - podman-docker
    - docker-compose
    - clang
    - cmake
    - build-essential
    - net-tools
    - autoconf

- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
