proxmox:
  hosts:
    proxmox-0:
      ansible_port: 22
      ansible_host: 192.168.1.20
      ansible_user: root
    
vms:
  hosts:
    devbox.molest.ar:
      ansible_port: 22
      ansible_host: 192.168.1.205
      ansible_user: galera
    template:
      ansible_port: 22
      ansible_host: 192.168.1.190
      ansible_user: galera
