- name: Install Podman
  ansible.builtin.apt:
    pkg:
    - podman
    - uidmap
    - slirp4netns
    - podman-docker
    - podman-compose
    install_recommends: true # Don't install graphical packages
