- name: Install KVM
  ansible.builtin.apt:
    pkg:
    - qemu-system
    - libvirt-clients
    - libvirt-daemon-system
    install_recommends: false # Don't install graphical packages

- name: Ensure the "libvirt" group exists
  ansible.builtin.group:
    name: libvirt
    state: present

- name: Add the user to the "libvirt" group
  ansible.builtin.user:
    name: galera
    groups: libvirt
    append: yes  # Append the group membership; don't remove from other groups
