# playbook.yml
---
- name: Common
  hosts: all
  become: yes
  become_method: su # Needs to be su as some systems don't have sudo installed
  gather_facts: yes
  
  pre_tasks:
    - name: Ensure the system is updated before proceeding
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - role: common
      vars:
        host_user: galera
