# playbook.yml
---
- name: Common
  hosts: all
  become: yes # Use privilege escalation (e.g., sudo) if needed for task execution
  become_method: su
  gather_facts: yes # Collect system facts; set to no if not needed to save time
  
  # Optional: Pre-tasks run before the main role or tasks
  pre_tasks:
    - name: Ensure the system is updated before proceeding
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - role: common
      vars:
        host_user: galera
