# HAProxy
---
- name: HAProxy
  hosts: proxy.ams.molest.ar
  become: yes
  become_method: sudo
  gather_facts: yes
  
  # Optional: Pre-tasks run before the main role or tasks
  pre_tasks:
    - name: Ensure the system is updated before proceeding
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - role: common
    - role: network
    - role: haproxy
