---
- name: Proxmox playbook
  hosts: all
  become: yes
  become_method: su
  gather_facts: yes
  
  pre_tasks:
    - name: Ensure the system is updated before proceeding
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - role: common
      vars:
        host_user: root
    - role: hostname
      vars:
        hostname: "proxmox.ams.molest.ar"
